# Site settings
title: The Visualization Picayune
email: butterwell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about visualization which sometimes focuses on nearly trivial details.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://butterwell.github.io" # the base hostname & protocol for your site
twitter_username: butterwell
github_username:  butterwell
author: Christopher Michael Buck
permalink: /:title/
#permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
